# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5de5a6d0d9fc5db639a519a1f5023027098628da2923e4a8388d6746a152e711ef85eedd73d8dd78681db3b523098ed0d992c875e1adea8837b6d843d7a081f

test:
  secret_key_base: 1881e9e6a9898e0ab1108c876b46c5b9b64e13c53249997c1ef44f2cd39cb1ca23268159e1848d95aa1fdf12cc230068ef98f2c472767d40a0455dba048243dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
